mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.qg24.softwareplatform.mybatis.entity
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/software_platform
    redis:
        host: localhost
        port: 6379
        database: 0
        username: default
        password: 123456
email:
    host: smtp.qq.com
    password: ecxcdzqqmwslddcj
    username: 3087609114@qq.com
    port: 587
alioss:
    bucket-name: faken
    access-key-secret: EePxVtk99UdGJMxOtaOZeUSrdMqSGK
    access-key-id: LTAI5tQ717VX5w1AMvos7M1A
    endpoint: oss-cn-guangzhou.aliyuncs.com







